### ISSUE TITLE
SendSample - Need some update.

### ISSUE THREAD

**Issue by datauduong** [Azure/azure-service-bus-dotnet#133]
## Actual Behavior
1. Try Compile Send Sample getting an Error Message in the 
project.json was "Microsoft.Azure.ServiceBus": "0.0.2-preview"

2. Does not have build target platform build specify in project.json, therefore Can't Compile

3. When Sending to Queue with Session Enable, I get an error message.
Exception: Put token failed. status-code: 404, status-description: The messaging entity 'sb://dataflow.servicebus.windows.net/exchangedata' could not be found. TrackingId:919bf951-f1c1-4e50-901e-243735c310a3_G15, SystemTracker:dataflow.servicebus.windows.net:exchangedata, Timestamp:4/17/2017 11:46:26 AM.

## Expected Behavior
1. Changed to "Microsoft.Azure.ServiceBus": "0.0.4-preview"

2. I have done a search from google and found that I Need to add the following to project.json in the SendSample.

// Tried the following and it work.
"runtimes": {
    "win10-x86": {},
    "win10-x64": {}
  } 
or
// Haven't try the following
"type":"platform"

3. In the SendMessagesToQueue function, I have added SessionId, but does not work.
What do I need to do to make it work for Send/Receive with Session Enable Queue ?

## Versions  
- OS platform and version: Windows 10 x64
- .NET Version: 4.5.1
- NuGet package version or commit ID: Dev Branch (Cloned 8256e83)

**Comment by jtaubensee** [comment]
@datauduong - Thanks for checking out the samples. Let's take a look at each question:

> 1. Try Compile Send Sample getting an Error Message in the
project.json was "Microsoft.Azure.ServiceBus": "0.0.2-preview"

Since the samples are included in a Visual Studio solution, you (and probably every one) else is getting a warning saying that it ended up with a higher dependency than what was specified. That is OK, as the current version in the project, is `0.0.4`.

> 2. Does not have build target platform build specify in project.json, therefore Can't Compile

Where are you trying to run/build this application? For example, if you download the solution and build as is, you shouldn't have any issue. If you want to build the sample as an executable that you can take to another machine (without building it there), then you will need to specify the target.

> 3. When Sending to Queue with Session Enable, I get an error message.
Exception: Put token failed. status-code: 404, status-description: The messaging entity 'sb://dataflow.servicebus.windows.net/exchangedata' could not be found. TrackingId:919bf951-f1c1-4e50-901e-243735c310a3_G15, SystemTracker:dataflow.servicebus.windows.net:exchangedata, Timestamp:4/17/2017 11:46:26 AM.

Do you have sessions enabled on this entity?

![2017-04-17_10h57_00](https://cloud.githubusercontent.com/assets/8162917/25098226/9cd3d948-235c-11e7-9485-593be06d2734.png)
