### ISSUE TITLE
The link to the NuGet package in the readme points to the wrong package

### ISSUE THREAD

**Issue by jeroenlandheer** [Azure/azure-service-bus-dotnet#147]
Link should be: NuGet package - https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/
(Current link points to the management client, which is used to manage the service bus service in Azure)

**Comment by jtaubensee** [comment]
The links that you are referring to are a part of the question "Can I manage Service Bus entities with this library?", so that is correct.

https://github.com/Azure/azure-service-bus-dotnet#can-i-manage-service-bus-entities-with-this-library

If you are looking for the NuGet package for this client, you can click on the NuGet version badge in the Build/Package table.

![2017-04-27_10h54_33](https://cloud.githubusercontent.com/assets/8162917/25496999/f1c85aea-2b37-11e7-8e75-9e42b19abc65.png)

**Comment by jeroenlandheer** [comment]
Whoops, I guess I looked over that one :) Thank you 👍
