### ISSUE TITLE
PeekBatch support

### ISSUE THREAD

**Issue by bmmathe** [Azure/azure-service-bus-dotnet#148]
The full framework Azure Service Bus client has the capability to PeekBatch a queue which lets the client read once from a queue and does not lock the message.  This is perfect for monitoring behavior where you need a view of the queue for troubleshooting without actually trying to process the message.  I'm trying to figure out a way to mimic this behavior with this library using the QueueClient but I can't come up with any great ideas.  What I'm trying to do is create a service that will return the contents of a queue and the messages.  RegisterMessageHandler seems to be more of a listener rather than "get me x items from the queue".

Is PeekBatch(int count) going to be supported or is there a way to get something similar to work without calling RegisterMessageHandler each time my service endpoint is hit?  Even if I did RegisterMessageHandler how would I know when to close the connection?  Would it be appropriate to just set a count then close the Handler once I fill a list up to that count?  What if the total count in the queue is less than the count specified?  How would I know when it's finished reading the queue?

**Comment by jtaubensee** [comment]
@bmmathe - #146 will allow you to use the `MessageReceiver`, which has support for `Peek()`. It is safe to say that this will be in the next release. `Peek()` was intentionally kept out of the `Queue`/`Subscription` clients, because there are performance implications, and it can potentially lead to bad practices. i.e. peeking messages regularly, and looking for the one you want (something we want users to avoid all together). In your case, using it for checking the status of a queue is appropriate.
