### ISSUE TITLE
Support SAS token

### ISSUE THREAD

**Issue by binzywu** [Azure/azure-service-bus-dotnet#185]
## Actual Behavior
1. Client client doesn't support SAS token

## Expected Behavior
1. Client client supports SAS token

## Versions  
- OS platform and version: N/A
- .NET Version: N/A
- NuGet package version or commit ID: 0.0.6-preview

**Comment by vinaysurya** [comment]
Its already supported today

**Comment by Blackbaud-MitchellThomas** [comment]
If it's already supported today, is there an example of how to accomplish it?

I've been digging into this for a while, and what I've found is that while SAS tokens are in use internal to the clients, the the ability to create a client from an externally generated SAS token isn't available. For example, I want to grant an external consumer access to a single subscription on a topic by giving them a token instead of an access key.

**Comment by hbiarge** [comment]
I have the same requirement. Can you point to any example of use with SAS tokens?

**Comment by Blackbaud-MitchellThomas** [comment]
@vinaysurya, are there any resources available to shine some light on this?

**Comment by nemakam** [comment]
@hbiarge @Blackbaud-MitchellThomas, 
You are right. The E2E integration is not complete with SAS tokens. Since this thread is already closed, look at #332 for updates.
