### ISSUE TITLE
Message.UserProperties is about custom properties, not user

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#198]
Currently, `Message` defines two property collections:
1. System properties represented by `message.SystemProperties`
1. Custom properties represented by `message.UserProperties`

Documentation and standard nomenclature for brokered messaging doesn't use "user" properties. Therefore for consistency, suggest to rename `message.UserProperties` to `message.CustomProperties`.

**Comment by SeanFeldman** [comment]
@binzywu considering that there are no more issues for `1.0.0` milestone, this will be a breaking change that can't be made until next major, `2.0.0` according to SemVer. Should this be included in `1.0.0`?

**Comment by abombss** [comment]
The User nomenclature probably comes from the fully qualified name reference required when using Actions and Filters for these custom headers.  I would recommend keeping User given its a breaking change at this point, and just update documentation to reflect User instead of Custom.  Especially since that has been establish usage in Rules and Actions since the beginning of service bus.

> \<scope\> is an optional string indicating the scope of the <property_name>. Valid values are sys or user. The sys value indicates system scope where <property_name> is a public property name of the BrokeredMessage Class. user indicates user scope where <property_name> is a key of the BrokeredMessage Class dictionary. user scope is the default scope if <scope> is not specified.

**Comment by SeanFeldman** [comment]
@abombss this issue is no longer relevant since 1.0 has been shipped 😃 `UserProperties` it is.
Can be closed.
