### ISSUE TITLE
what is the substitute of MessagingEntityAlreadyExistsException in the new management library

### ISSUE THREAD

**Issue by barkhashah** [Azure/azure-service-bus-dotnet#254]
if the subscription resource already exists then what kind of exception be thrown by the new library? Old library had MessagingEntityAlreadyExistsException but this seems to be missing in the new implementation.

I am using this method to create the subscription:

public static Task<SBSubscription> CreateOrUpdateAsync(this ISubscriptionsOperations operations, string resourceGroupName, string namespaceName, string topicName, string subscriptionName, SBSubscription parameters, CancellationToken cancellationToken = default(CancellationToken));

**Comment by SeanFeldman** [comment]
@barkhashah this repo is **not** dealing with entity management API. You raise your questions in the wrong repo 🙂 Repository you want is https://github.com/Azure/azure-sdk-for-net/

**Comment by ElanHasson** [comment]
@barkhashah  did you find the answer to this? The other repo doesn't have the question.

**Comment by SeanFeldman** [comment]
@ElanHasson since this library doesn't provide management API, this exception **cannot** contain replacement for `MessagingEntityAlreadyExistsException`. If you follow my [comment](https://github.com/Azure/azure-service-bus-dotnet/issues/254#issuecomment-320357620), you'll see that the exception in question is not needed since you are going to identify if entity exists or not when using API library. See a snippet I've provided [here](https://github.com/Azure/azure-service-bus-dotnet/issues/65#issuecomment-325899160).
