### ISSUE TITLE
MessageReceiver.ReceiveAsync throws ServiceBusTimeoutException if passed with Timespan.Zero

### ISSUE THREAD

**Issue by shahbarkha** [Azure/azure-service-bus-dotnet#294]
In your sample application :\azure-service-bus\samples\DotNet\Microsoft.Azure.ServiceBus\SendReceiveUsingMessageSenderReceiver

Please try to pass Timespan.Zero in the ReceiveAsync method. 

Actual Behavior - Exception gets thrown. 

An unhandled exception of type 'Microsoft.Azure.ServiceBus.Primitives.ServiceBusTimeoutException' occurred in System.Private.CoreLib.ni.dll
Timed out trying to create FaultTolerantAmqpObject`1

Expected Behavior - Should it not retrun null? What does it mean to pass TimeSpan.Zero in the ReceiveAsync method?

Message message = await messageReceiver.ReceiveAsync(TimeSpan.Zero);

**Comment by SeanFeldman** [comment]
`null` would be returned if the invoked `this.ReceiveAsync(1, operationTimeout)` would not fail. But it fails with the underlying exception is  `Timed out trying to create FaultTolerantAmqpObject`1`. That's because `ReceiveAsync(int maxMessageCount, TimeSpan operationTimeout)` is subsequently invoked with `TimeSpan.Zero` for the `operationTimeout`. That one is passed further into `this.OnReceiveAsync()` call. When [`ReceiveLink`](https://github.com/SeanFeldman/azure-service-bus-dotnet/blob/b4285e5b436f0574810c49cacdd9973e214d155c/src/Microsoft.Azure.ServiceBus/Core/MessageReceiver.cs#L789) is created, it throws as timeout has already occurred (timespan of zero).

I'd say `ReceiveAsync()` should not accept `TimeSpan.Zero`.

**Comment by niemyjski** [comment]
@SeanFeldman, I agree. Any timespan value should be properly handled with argument validation or from the service. TimeSpan.Zero is a valid value saying I do not wish to timeout. If it's not supported server side an ArgumentException should be the proper course.

@barkhashah perhaps if our implementation contains should check for TimeSpan.Ticks <= 0 and not pass a timeout value? @SeanFeldman, do you know off the top of your head if you even pass this through if it's negative? Perhaps it's just ignored if it's 0 or negative timespan, but the counter argument is fail fast.

**Comment by SeanFeldman** [comment]
Currently `MessageReceiver` passes the value as is. I've raised a PR to address waitTime that is less or equal to `TimeSpan.Zero` which I agree, shouldn't be accepted as a valid value.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Azure/azure-service-bus-dotnet/commit/e650ac4c4e69818fde7872ae4784df542c95d21b

**Comment by niemyjski** [comment]
Awesome Thanks!
