### ISSUE TITLE
Resources.resx

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#303]
Currently, exception messages are stored in resources file.
1. Is there intent to localize those exceptions?
1. Have there been any evidence that localizing exceptions improves the ability to search and find materials to fix the issue?

Thank you.

**Comment by SimonCropp** [comment]
some more context

 * https://stackoverflow.com/questions/929604/should-exception-messages-that-are-targeted-to-the-developer-be-localized
 * https://social.msdn.microsoft.com/Forums/en-US/d9aa2bc0-78c3-412a-877c-19d81ec43e8a/localization-of-exceptionmessages-is-harmful?forum=vstscode

**Comment by SeanFeldman** [comment]
Verdict? Happy to send a PR 🙂

**Comment by nemakam** [comment]
We are internally discussing this and are trying to figure out the standard practices across board that needs to be followed. For now, keep the PR efforts on hold.

**Comment by SimonCropp** [comment]
Minor point, but some consider behaviour like "internally discussing" to go against how an open source project should operate.

**Comment by nemakam** [comment]
Ack. I completely agree. But unfortunately we are in a world where not the entire company (in terms of users and code) is on github. This is a decision which involves not just this repo, but also other language clients, and the old client which is not even open source.

**Comment by SimonCropp** [comment]
Tbh i would really like to see "dont localize exception" broadly adopted at MS. From the consumer perspective it has always delivered a net negative value. For that negative value we pay a cost in complexity, code base size, compile time, assembly size, assembly load time, performance, extra effort to continually code against the pattern etc. i realize some of those impacts are very, but combined it seems sensible to just burn the whole lot

**Comment by SimonCropp** [comment]
not to mention that much of the community at large tries to follow that pattern

**Comment by tomzorz** [comment]
Definitely "+1" for the side of no localization. Every single time I had a localized error pop up in Hungarian it only made things harder to fix.

**Comment by SimonCropp** [comment]
I have actually seen some devs who run a windows VM in US local to avoid these kinds of issues.

**Comment by SeanFeldman** [comment]
@nemakam will this be included in `2.0`?

**Comment by nemakam** [comment]
It can be. Depends on when this gets checked in. 
The way I see it, this is a non-blocker. If it gets in by 2.0, great! Else the next version.

**Comment by clemensv** [comment]
Having these messages externalized also makes typo fixes or across-the-board legibility improvements easier without having to change 20 files.

Whether you all personally don't want localization into languages other than English doesn't change the fact that a translation may be required for compliance reasons in certain world regions/countries, and that exceptions occasionally roll up into logs/messages read by non-developers who are less likely to understand English. 

If you don't want messages pop up in a message you don't understand, don't run in that locale.

Now: I am in favor of us adding some sort of identifier as suffix into the exception text, so that if you get a bug report from a German customer with an exception text included, you can tell what message that is even if you don't understand the text. Eg.

The provided token does not specify the 'ExpiresOn' value. (23) 
Das übergebene Token enthält keinen 'ExpiresOn' Wert (23)

That'd be different bug, though, and doesn't seem to be worth time doing until we'd actually add loc.

Closed as "wontfix"
