### ISSUE TITLE
 new Guid(lockToken) ?

### ISSUE THREAD

**Issue by SimonCropp** [Azure/azure-service-bus-dotnet#321]
it seems all the variable passing of locktokens is via a string. but then in the fast path it always seems to be converted to a guid

```
AmqpMessageConverter.cs(325):                sbMessage.SystemProperties.LockTokenGuid = new Guid(guidBuffer);
MessageReceiver.cs(977):            var lockTokenGuids = lockTokens.Select(lt => new Guid(lt)).ToArray();
MessageReceiver.cs(987):            var lockTokens = new[] { new Guid(lockToken) };
MessageReceiver.cs(997):            var lockTokens = new[] { new Guid(lockToken) };
MessageReceiver.cs(1007):            var lockTokens = new[] { new Guid(lockToken) };
MessageReceiver.cs(1022):                amqpRequestMessage.Map[ManagementConstants.Properties.LockTokens] = new[] { new Guid(lockToken) };
```

why not convert it to a guid asap and then pass that around and save on the multiple guid parsing?

**Comment by nemakam** [comment]
@SimonCropp , didnt get you? 
Are you suggesting we are doing the conversion from string to GUID multiple times?
Are you suggesting we are generating more objects?

We receive and send using GUID at the AMQP layer. The uber aim of the translation was to provide user with only string instead of GUID so that he can store in any data layer or maybe pass it to another system running on a different platform over the wire. GUID is a net concept and isnt present in other platforms, say Java.

**Comment by SimonCropp** [comment]
> Are you suggesting we are doing the conversion from string to GUID multiple times?
> Are you suggesting we are generating more objects?

yes and yes.

I did a temp PR to illustrate the problem https://github.com/SimonCropp/azure-service-bus-dotnet/pull/1/files

 * removes 5 `new Guid()`. of which one was in a loop
 * removes one extra array allocation
 * reduces the chance of one of those `new Guid(` throwing a parse exception
 * provides a stronger typed API
 * same amount of code

> We receive and send using GUID at the AMQP layer. The uber aim of the translation was to provide user with only string instead of GUID so that he can store in any data layer or maybe pass it to another system running on a different platform over the wire. GUID is a net concept and isnt present in other platforms, say Java.

other platforms can still do this irrespective of the .net api

**Comment by nemakam** [comment]
@SimonCropp , looking at your PR, I now understand what you mean. But like I said, the conversion from GUID to string was intentional. If you have used our older libraries, you can see that we do return GUID and expect GUID for methods like `completeAsync` or `AbandonAsync` etc. But we decided to change that for the new client.

The rational behind it is 2 folds:
1. string is easier when it comes to sending across platforms and machines and is universally more consistent unlike GUID. 
2. The current code allows the possibility of extension in case we plan future improvements. Consider the following strictly as an example and not as a future plan - Currently each client has only one connection underneath in which send and receive happens. Let say we decide to have multiple connections (as a pool) in a single client. Now based on how AMQP works, we can complete a message only on the same link as it was received. So in case of connection pooling, we need to know which connection was used to receive a given message. Scenarios like this can be handled if we can stamp additional information on to the lockToken string and then remove them before converting them to GUID back.

**Comment by SimonCropp** [comment]
> If you have used our older libraries, you can see that we do return GUID and expect GUID for methods like completeAsync or AbandonAsync etc. But we decided to change that for the new client.

But you havnt actually achieved anything. your premise is you now support strings that are not a guid. but the first time someone tries to do that the first `new guid(string)` that is hit will throw a very unhelpful exception.

**Comment by SimonCropp** [comment]
> The current code allows the possibility of extension in case we plan future improvements. Consider the following strictly as an example and not as a future plan - Currently each client has only one connection underneath in which send and receive happens. Let say we decide to have multiple connections (as a pool) in a single client.

This sounds like a dangerous premature optimisation. if you do want to go down that path i suggest u document and smoke test a real sample implementation of that scenario prior to making architectural decisions based on what you think is possible

**Comment by nemakam** [comment]
> the first time someone tries to do that the first new guid(string) that is hit will throw a very unhelpful exception.

Finding solutions to this problem is easier. Do a try parse right in the beginning and throw a very nice super meaningful error if its not able to.

**Comment by SimonCropp** [comment]
if u really want to support non guid why not make them strings all the way down?

**Comment by nemakam** [comment]
> This sounds like a dangerous premature optimisation. if you do want to go down that path i suggest u document and smoke test a real sample implementation of that scenario prior to making architectural decisions based on what you think is possible

Well, you clearly didnt go through the sentence `Consider the following strictly as an example and not as a future plan`

I'd like to understand what is the downside of this that you are worried about. Is it about doing a GUID -> string -> GUID conversion? IMO, this conversion is worth it if it helps you from multiple possible issues . Either way, the product is already GA, and changing all the signatures to avoid a conversion is plain wrong.

**Comment by clemensv** [comment]
Our protocol implementation under the hood and the surface area are two different things. 

The underlying protocol takes amqp:uuid as type or the lock management gestures. The protocol design catches early that a client doesn't send completely nonsensical information; at a minimum you have to make a uuid and that's the indexing type in our backend. See all [lock-related ops here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response).

We might, however, decide in a protocol upgrade to change our mind on this and use a different type, require extra information, or we might plumb an extra protocol that doesn't have a native GUID type. That's not a premature optimization; AMQP is an outlier in having a native type system with uuid support. That is all to say: You are seeing one example of a mapping of the lock token to a protocol because it's currently the only one, but that doesn't mean it will forever stay that way. When we design APIs we generally prioritize API stability over performance gains of this sort.

The LockToken is an opaque string that the app is supposed to roundtrip without reasoning about it. We could arguably have made it a byte[] or even plain object to emphasize that, but that ship has sailed.

I'm closing this issue as "wontfix". I hope that doesn't discourage you from further feedback. Thank you very much for raising this.
