### ISSUE TITLE
Socket errors with ServiceBus client

### ISSUE THREAD

**Issue by odysseus1973** [Azure/azure-service-bus-dotnet#360]
Hi!

Since yesterday I began to receive many exceptions 

`An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full ErrorCode: NoBufferSpaceAvailableAn operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full`

```
Microsoft.Azure.ServiceBus.ServiceBusCommunicationException
--
Microsoft.Azure.ServiceBus.Core.MessageSender+<OnSendAsync>d__40.MoveNext
[external code]
API.Helpers.ServiceBusQueueClient+<SendMessageAsync>d__6`1.MoveNext
[external code]
API.Controllers.StocksController+<UpdateStocks>d__7.MoveNext
```

Why this can be?

**Comment by nemakam** [comment]
This is an OS level setting issue and not related to ServiceBus client... 
You could find this issue and solutions in stackoverflow and other blogs.

https://stackoverflow.com/questions/4415175/an-operation-on-a-socket-could-not-be-performed-because-the-system-lacked-suffi 
https://blogs.msdn.microsoft.com/sql_protocols/2009/03/09/understanding-the-error-an-operation-on-a-socket-could-not-be-performed-because-the-system-lacked-sufficient-buffer-space-or-because-a-queue-was-full/

Reopen the issue if you think our client is inducing this or requires some changes...
