### ISSUE TITLE
Public API validation

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#40]
Related to #39 

Minimal public API surface area validation should be automated to ensure that no internal types leaked out.
Suggest we look into [API Approver](https://github.com/JakeGinnivan/ApiApprover) to control the public API surface area, when API Approver supports .NET Standard.

/cc @jtaubensee

**Comment by jtaubensee** [comment]
On Hold as the library referenced does not support .NET Core/Standard.

**Comment by jtaubensee** [comment]
Let's close this for now, no need to keep an issue open for a library that may or may not support .NET core. This is something we can revisit when the library is closer to GA. While we want to limit the API changes as much as possible, we dont currently have a contract since the library is in preview.

**Comment by jtaubensee** [comment]
Since we are now running unit tests against .net 4.6 again, we can have a compiler directive to only run this against .net 4.6. Assigning to @SeanFeldman to take care of.

**Comment by SeanFeldman** [comment]
It will be possible to enable API approval for netstandard2.0 when https://github.com/approvals/ApprovalTests.Net/issues/162 will be addressed.
