### ISSUE TITLE
The client doesn't take into consideration plugins disposal

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#440]
[`ServiceBusPlugin`](https://github.com/SeanFeldman/azure-service-bus-dotnet/blob/b44265e233c9d950035a749c1a2f55600398fc26/src/Microsoft.Azure.ServiceBus/Core/ServiceBusPlugin.cs#L11) can be registered with one of the [`IClientEntity`](https://github.com/SeanFeldman/azure-service-bus-dotnet/blob/b44265e233c9d950035a749c1a2f55600398fc26/src/Microsoft.Azure.ServiceBus/IClientEntity.cs#L46) implementors or unregistered, but there's nothing that would cause resources disposal, if any allocated by plugins.

This was brought with [ServiceBus.AttachmentPlugin](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/issues/36) that is using [`SemaphorSlim`](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/593b212222fe5aac718d9622167befca73b08eb8/src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs#L13) which is `IDisposable`. Best practice for .NET is to implement `IDisposable` for any type that allocates memory or usese internally types that implent `IDisposable`.

[`IClientEntity.OnClose()`](https://github.com/SeanFeldman/azure-service-bus-dotnet/blob/b44265e233c9d950035a749c1a2f55600398fc26/src/Microsoft.Azure.ServiceBus/IClientEntity.cs#L35) which can be invoked on any specific-type client, is calling [`OnClosingAsync`](https://github.com/SeanFeldman/azure-service-bus-dotnet/blob/b44265e233c9d950035a749c1a2f55600398fc26/src/Microsoft.Azure.ServiceBus/ClientEntity.cs#L106), which should dispose any registered plugin.

## Proposed changes

1. Introduce `IDisposable` on `ServiceBusPlugin`.
1. Include this fix for the next major (v3) as this is a breaking change.

**Comment by SeanFeldman** [comment]
Will be happy to send a PR.

**Comment by SimonCropp** [comment]
+1 given an app could spin up and tear down many client context on demand, not allowing a plugin to utilise dispose semantics could be considered a memory leak

**Comment by SimonCropp** [comment]
> We avoid IDisposable on the clients to discourage recreating clients (since it creates new connections.). Once we start having plugins in IDisposable format, the whole discouragement is kinda lost.

IDisposable  in no way conveys "should be short lived". While this is a common misconception, building an API on top of poor understanding of a concept is not a good way to go, as it compounds the problem instead of educating people as the correct approach. That clients should be long lived should be explicitly called out in doco. And there is a existing decision already in the .net framework... 
 HttpClient is IDisposable but should be long lived. https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

> The interface becomes inconsistent, as few elements are disposable, whereas few have to be closed manually.

not sure i understand

> One of the options could be expose OnClosingAsync() for each plugin (through interface). This will be called when clientEntity.Close() is called. But then in that case, we end up forcing customers to create a new plugin for each queue client, and they cant be shared anymore.

I dont think this "forcing new plugin for each queue client". if u pass the queue client instance back in as a param to OnClosingAsync then it clear that it is a possibly multi client api?

> Solution I can think of is exposing Close() or similar functionality in the plugin itself, that the customers are expected to call. It is slightly against the disposable rule, but at least things would be consistent.

doesnt this fall into the "we end up forcing customers to create a new plugin for each queue client"?

**Comment by nemakam** [comment]
> IDisposable in no way conveys "should be short lived". While this is a common misconception, building an API on top of poor understanding of a concept is not a good way to go, as it compounds the problem instead of educating people as the correct approach. That clients should be long lived should be explicitly called out in doco. And there is a existing decision already in the .net framework...
HttpClient is IDisposable but should be long lived. https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

Your statement already answers lot of the reasoning. IDisposable being a 'short lived' object is a very famous misconception. Lot of code checkers and refactoring extensions also actively promote to wrap them inside `using()` block. I agree it is the framework team's responsibility to document it, but by no means that would stop people from wrapping things within `using`. And, in this particular case, we are not a framework team, we are the service providers. We know how expensive each of those create connection calls are on the service when you start including authentication, resolution of the partitions, establishing a new link from gateway to the broker. We also know how many of our customers have followed the "best practices" on the docs while creating an app to invoke service bus. 
Lot of the decisions here are made based on how our customers use our service. And we do understand that not every decision is ideal for everyone. I'd appreciate if we can have a healthy debate instead of calling names. 

> not sure i understand

If you get back to the assumption that there will always be developers who wrap things within `using`, then you can see that the usage becomes tricky when you wrap plugins within `using` and not the clients. 

> I dont think this "forcing new plugin for each queue client". if u pass the queue client instance back in as a param to OnClosingAsync then it clear that it is a possibly multi client api?

The point is about 'who' is responsible to call `plugin.Close()` or `plugin.Dispose()`? If you let the `IClientEntity` do it, then the plugin becomes per client object. The alternate is developer calling the method himself. If that is the case, then what we need to answer is whether this is a plugin specific code change or changes that can be generalized to all the plugins.

**Comment by nemakam** [comment]
@SeanFeldman 
I guess we agree on the part that it is developer's responsibility to close/dispose. 

Now the second part of question. Is this something that is generic to all the plugins? i.e., should individual client implement `IDisposable`, or should it be enforced? 
IMO, there will be lot of plugins that might not have anything to dispose. `MessageIdGenerator` is a classic example. So maybe `IDisposable` should be on the individual plugin itself and not on `ServiceBusPlugin` class?

**Comment by SeanFeldman** [comment]
> Is this something that is generic to all the plugins

If we end up with a decision that it's a developer responsibility to dispose a plugin, then probably doesn't make sense to enforce on all plugins this model. Before we seal anything, I'd like to poke holes in this idea. @SimonCropp please chime in.

**Comment by SimonCropp** [comment]
@SeanFeldman so if the developer is in charge of lifetime/cleanup of a plugin, how would that work in your  use case https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/develop/src/ServiceBus.AttachmentPlugin/AzureStorageAttachmentExtensions.cs#L14

since the developer has no access to the `AzureStorageAttachment`

**Comment by SeanFeldman** [comment]
@SimonCropp true that. Though it was a deliberate design decision to abstract the actual plugin implementaton from users to be able to easily change it over time w/o worrying for breaking changes.

Attachment Plugin original design implies that each time a new instance is created rather than reused. Now I wonder if that's a correct design and wherever it should be modified. `AzureStorageAttachmentExtensions` could return an `IDisposable` so that there's a reference and ability to `Dispose()`. ATM, the plugin doesn't allow re-use of an already registered instance.

**Comment by SeanFeldman** [comment]
So there are a few things on the table:
- Should the client even bother to manage lifecycle of plugins?
- Should `ServiceBusPlugin` impose any opinion on how plugins are managed by implementing `IDisposable` or some sort of `CloseAsync()`
- Or leave that entirey to the plugins?
  - A plugin that doesn't have anything disposable doesn't need to be "punished" and forced to implement anything it doesn't do.
  - Arguably, whoever is registering plugins is in charge of the plugin lifecycle.

**Comment by nemakam** [comment]
>Should the client even bother to manage lifecycle of plugins?

No. Since we don't want to force 1 plugin instance per client.

> Should ServiceBusPlugin impose any opinion on how plugins are managed by implementing IDisposable or some sort of CloseAsync()

IMO No, since it doesnt really apply to all the plugins. I think these should be left to the plugin owner how he wants his plugin to be used. I look at `ServiceBusPlugin` as a point where plugin developer needs some help into hooking into our client. It doesn't really dictate the lifecycle of the plugin.

**Comment by SeanFeldman** [comment]
With  ServiceBus.AttachmentPlugin plugin I took the approach of [explicit disposal](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/pull/38#issue-182066636) on the plugin level. Therefore this issue is relevant. @nemakam feel free to close.
