### ISSUE TITLE
Review conditional inclusion of tests

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#454]
Some tests are only executed for a specific target framework, `net461` or `netcoreapp2.0`.
Is that correct though? Some tests should be fine to run with both frameworks. For example `RetryTests.cs`.
Re-evaluate this and see what tests really require a specific target framework vs tests that can run for both.

![image](https://user-images.githubusercontent.com/1309622/39561298-0809244e-4e62-11e8-827f-0ca071c3e2af.png)

**Comment by nemakam** [comment]
All the tests should successfully run in all the targets. Things have been made this way since AppVeyor doesn't work if total time crosses 1 hour. And if we run all the tests for both the frameworks, then we definitely cross 1 hour. Hence this approach. 
Regarding tests like `RetryTests` there is literally no reason why we want to run in both the frameworks. The only thing that differs in frameworks are things like network / communication / websockets etc. Those need to run on both the frameworks. Maybe transactions as well. So as long as we have at least one test which tests network / communication in each of the framework, we should be good.
Which is already the case. Don't you think?

**Comment by SeanFeldman** [comment]
> Regarding tests like RetryTests there is literally no reason why we want to run in both the frameworks.

Document it. Adding a `<!-- Enough to validate these with one target framework to avoid AppVeyor 1h execution limit -->` 🙂 

> All the tests should successfully run in all the targets

I've raised a [question](https://help.appveyor.com/discussions/questions/20091-build-time-limitation) about time limitation. Feels odd that 1h is a limit for paid options as well. There's an interesting option of  [running builds as a local process](https://www.appveyor.com/docs/enterprise/running-builds-as-local-process/) which _could_ be done using an Azure VM or something if it would allow extended execution times.

**Comment by SeanFeldman** [comment]
@nemakam you might want to look into the response I got

> Increasing build time to 90 minutes is typically not a big deal. If you need even longer build times, there is a [private build cloud option](https://www.appveyor.com/docs/build-environment/#private-build-cloud), that allows you to set your own build time in UI for any builds on your pirvate build cloud.

**Comment by nemakam** [comment]
Awesome :)

**Comment by SeanFeldman** [comment]
You're welcome.
We accept cash, cheques, and credit cards 😜
