### ISSUE TITLE
What's the purpose of batchable in AmqpMessageConverter.BatchSBMessagesAsAmqpMessage?

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#534]
The method is passed in a parameter, `batchable` which is always `true`.
What the purpose of this parameter and can it be `false` at all given the current code?

**Comment by nemakam** [comment]
Take a look at: http://www.amqp.org/sites/amqp.org/files/amqp.pdf  Section `2.7.5` for better understanding.

The true / false depends on how we want to approach this on the service regarding batching of dispositions. Batching of dispositions help increase the throughput but can affect the latency. 
In our older clients we used to provide sync and async methods to send messages. During async, we batched the messages and for sync we didnt. The method was taken from the previous client as is and since the new client is completely async, the only value used in this case is batchable=true.

**Comment by SeanFeldman** [comment]
In that case I'd suggest to remove the parameter and leave this issue
opened as `refactoring`
