### ISSUE TITLE
Message scheduling and cancellation

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-service-bus-dotnet#55]
I believe this is covered for "Sprint 5: Early 2017" but just checking in to see if this functionality is planned. I need functionality as discussed in [Canceling Scheduled Messages](https://blogs.msdn.microsoft.com/servicebus/2016/07/11/cross-post-canceling-scheduled-messages/) and I assume the `SequenceNumber` property is not valid for using to cancel as suggested in the article.

Is the API for `ScheduleMessageAsync` and `CancelScheduledMessageAsync` expected to come under Sprint 5?

Thanks for the great work and looking forward to trying this out with .NET Core :)

**Comment by SeanFeldman** [comment]
Would be also nice to see this functionality with `MessageSender` for the cases where messages sent to both queues and topics.

**Comment by jtaubensee** [comment]
@damienpontifex - Yep, you can expect to see this in the coming weeks/months. I will leave this issue open since there isn't already another to track it.

@SeanFeldman - That's another issue at this point, as MessageSender/Receiver are currently abstract classes. https://github.com/Azure/azure-service-bus-dotnet/blob/master/src/Microsoft.Azure.ServiceBus/MessageSender.cs#L11

I'm guessing there will be a new issue filed shortly.....

**Comment by SeanFeldman** [comment]
> I'm guessing there will be a new issue filed shortly.....

Link? 😛

**Comment by SeanFeldman** [comment]
New issue raised here: #57

**Comment by jtaubensee** [comment]
Closing this issue based on PR #69
