### ISSUE TITLE
IMessageReceiver.ReceiveAsync hangs after peak load

### ISSUE THREAD

**Issue by RobEyres** [Azure/azure-service-bus-dotnet#571]
## Summary

We've been load testing our application pipeline with a standard ASB with 50 million messages. All seems good initially and we can process around 15,000 - 25,000 messages a minute but then after some time the call to receive batches hangs. 

If I start a new instance of the application, it successfully processes more messages (although the service bus instance does seem sluggish)

We're calling IMessageReceiver.ReceiveAsync with PeekLock, a batch size of 100 and a prefetch of 100. We then process the messages and call CompleteAsync or DeadLetter async on every message (depending on the individual message result).

We're using a single instance of IMessageReceiver.

Protocol: AMQP
PrefetchCount: 100
BatchSize: 100
ASB Tier: Standard
ReceiveMode: PeekLock
EntityType: Topic subscription / Partitioned / 5 Gb / batch enabled / lock duration @ 1 min

## Actual Behavior
1. IMessageReceiver.ReceiveAsync hangs after a duration of peak load
2. The connection seems to remain in a faulty state

## Expected Behavior
1. IMessageReceiver.ReceiveAsync should either fulfil the request or timeout
2. The connection should recover

## Versions  
- OS platform and version: Windows 10 / Service Fabric
- .NET Version: Core 2.04
- NuGet package version or commit ID: v3.1.0

**Comment by nemakam** [comment]
When you say 'hangs', could you give more details on it? 
The method is expected to throw TimeoutException after it hits the timeout limit. Does this happen? Have you ever encountered a timeout exception?
Are you sure the process is hanging on "ReceiveAsync" and not on "Complete/Abandon"?

**Comment by nemakam** [comment]
Also, if the application is hung for beyond the timeout value, then could you take a dump and share it?

**Comment by RobEyres** [comment]
Hi. Thanks for the reply.

Actually, I realise that 'hangs' is the wrong word. I've looked again at the logs and it's timed out after a minute as per the default timeout on the connection. The confusing thing was that we weren't getting any messages even though some existed in the subscription AND I expected that if I set a timeout limit then the client would throw a TimeoutException (or similar).

There are a couple of confusing things in relation to this API.

1. A null is returned instead of an empty list when no messages are found (can we distinguish between timeout and an empty queue / subscription) ?
2. The batch size is typically different to what's been asked for (I know this was addressed / explained in another issue)
3. It's unclear as to how batch size and prefetch should be configured together

The issue for me which we still haven't resolved is why the client would degrade in performance after a several hours of peak load. We've now run on a premium ASB and things seem better so this could be infrastructural and not client related, but when compared to the classic (framework) client the behaviour seems quite different.

**Comment by nemakam** [comment]
Non premium ASB runs on shared resource. It is really hard to predict the performance you would receive in your namespace. You may receive a good performance in test run 1, but the numbers could be very different in production, either since you are sharing resources with someone else, or the someone else is having a varied load. If you are concerned about the throughput/performance, testing on premium ASB would be the only way to go (which I see you have already tried).

> A null is returned instead of an empty list when no messages are found (can we distinguish between timeout and an empty queue / subscription) ?

Yes. This is the API that has been exposed. When no messages are found, the API returns null. There is no easy way to distinguish between timeout and empty queue. In general, timeout would mean an empty queue. To be sure, you could always invoke `ManagementClient.GetQueueRuntimeInfo` to figure out the current message count. To give you more details, in AMQP protocol the timeout is a client side behavior and not service side. It requests for a new message, and waits for `timeout` seconds before it bails out. Unlike a regular request-response based protocol, this is a streaming protocol and there is no "empty queue" indication. End-of-stream is not a valid option since there can be messages that gets pushed to the queue after your request. 

> The batch size is typically different to what's been asked for (I know this was addressed / explained in another issue)

Yes. This is a known issue.

> It's unclear as to how batch size and prefetch should be configured together

This requires you to try it out in your test environment. There is no one-size-fits-all for prefetch and batch size. Take a look at this - https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements

**Comment by nemakam** [comment]
@RobEyres 
is there something that has not been answered? Is the issue good to close?

**Comment by RobEyres** [comment]
@nemakam 

Thanks for the update. You've cleared a few things up for me and we've had a lot more success running on a premium ASB.

Happy to close this issue.
