### ISSUE TITLE
Delayed message in auto forward enabled queue

### ISSUE THREAD

**Issue by jungkms** [Azure/azure-service-bus-dotnet#626]
While sending a delayed message to an auto forward enabled queue, it throws following exception:
Is this expected behavior, or could anyone kindly review my configuration whether I miss anything?

- Exception
`type: System.InvalidOperationException`
`message: Cannot create a message browser on an entity with auto-forwarding enabled. `

- API used
``` 
ISenderClient :: Task<long> ScheduleMessageAsync(Message message, DateTimeOffset scheduleEnqueueTimeUtc);
```
- Primary queue:
```
PrimaryQueueConfiguration = new QueueConfiguration()
{
    ConnectionString = serviceBusConnectionString,
    DuplicateDetectionWindow = null,
    MaxPrefetch = 5,
    QueueName = appConfiguration.DevelopmentEnvironmentName + "primaryqueue",
    MessageSerializerSettings = CommonJsonSerializerSettings.ServiceBusMessage
};
```

- Autoforward-enabled queue:
```
Deduped5MinQueue = new QueueConfiguration()
{
    ConnectionString = serviceBusConnectionString,
    DuplicateDetectionWindow = TimeSpan.FromMinutes(5),
    MaxPrefetch = 5,
    QueueName = appConfiguration.DevelopmentEnvironmentName + "d5mqueue",
    MessageSerializerSettings = CommonJsonSerializerSettings.ServiceBusMessage,
    AutoForwardingTargetQueueName = appConfiguration.DevelopmentEnvironmentName + "primaryqueue"
};
```

- .NET Version: .net core 2.1
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus(3.1.1)

**Comment by SeanFeldman** [comment]
This works as expected. 
When using `ScheduleMessageAsync()` API, `SequenceNumber` of the message is returned. To get the sequence number, broker has to "read" it. Since original queue is set to auto-forward, reading/peeking from the original queue is forbidden. Hence the exception.

To send a scheduled message to an entity that has auto-forwarding enabled, you could set `ScheduledEnqueueTimeUtc` property of the message. The downside is that you want have the `SequenceNumber` if you wish to cancel that message earlier. You could raise a question in the [**broker** repo](https://github.com/Azure/azure-service-bus/issues) to see if that feature is possible.
