### ISSUE TITLE
SubscriptionClient - GetRules

### ISSUE THREAD

**Issue by papatoob** [Azure/azure-service-bus-dotnet#99]
Hello everyone and thanks for the effort here. 

First I want to state that I don't really have a lot of experience in working with the Azure Service Bus, so maybe I'm headed in the wrong direction. That said, will there be (or is there already) a way to remove rules from a SubscriptionClient without knowing their names? This could, of course, be achieved manually by iterating over the existing rules, but unfortunately I was not able to somehow retrieve them.

Thanks in advance,

Tobi

**Comment by jtaubensee** [comment]
@papatoob - Are you trying to do that in this library, which is `Microsoft.Azure.ServiceBus` and not the full .NET Framework library [`Microsoft.ServiceBus.Messaging`](https://docs.microsoft.com/dotnet/api/microsoft.servicebus.messaging.subscriptionclient) (which does not have a GitHub repo)?

Either way, it is not supported today, but it might be a relevant ask. Can you describe your scenario a little bit more?

In the meantime, you could delete the subscription, but that would also remove all the messages on it.

**Comment by papatoob** [comment]
@jtaubensee Thanks for getting back so quickly. I'm using this library; I included the whole project in my Visual Studio solution. Here's my scenario (we're working on a prototype, so it's not a production thing):

I need a "listener" on a service bus and decided to use a .NET Core console application that'll be hosted as a continuously running web job inside an Azure web app, so it's kind of a service. When this application starts to run (and therefore listen to the service bus) it'll create the SubscriptionClient object receiving the messages. We need, however, some filters since the listener inserts stuff into a database and this is only supposed to happen for some messages.

Now it is possible that the filter criteria changes from time to time (especially while we're still evaluating the whole thing). But when I restart the application and hereby create a new SubscriptionClient object that I then add the first filter to, I get an exception telling me that a filter with its name already exists. I find this a little confusing, since I thought the filters were attached to the specific SubscriptionClient object, but - getting that exception - that doesn't seem to be the case.

Of course at this point I can remove the filter first because I know its name. But what I'd really like to do would be to remove **all** filters and then only apply the ones needed in the current situation.

Or did I maybe get it all wrong?

I'm in Germany and it's already Friday night here, so I might not be able to answer immediately, but I'll be back to answer any further questions tomorrow.

Thanks for your time.

**Comment by jtaubensee** [comment]
@papatoob - No problem!

So just as queues, topics, and subscriptions are a service level construct, so are filters and actions. For example, when you create a new filter / rule, this is persisted in our service. That is because the service needs to continue routing messages to that subscription if your application becomes disconnected. So if you add a rule successfully, you can assume it will be there even after you are disconnected.

With that said, it sounds like you might want something more along the lines of `GetRulesAsync()` that will allow you to check for your particular rule, before creating it. We don't have this today, as we have removed "management" functionality, and this was considered management in the past. We can potentially add this, but it will take some service side work to do so. In the meantime, you can wrap the `AddRuleAsync()` method in a try catch block.

Getting back to removing all the filters though... Do you care about messages on the subscription when your application isnt running? If you don't you can create a new subscription for each application (and the associated filters), and set `AutoDeleteOnIdle`, which will clean up your subscriptions after a period of inactivity. In order to get that management functionality (of creating subscriptions on demand) you can use this library: https://github.com/Azure-Samples/service-bus-dotnet-management

**Comment by papatoob** [comment]
@jtaubensee Hi John, thanks for the detailed explanation. And you're right about `GetRulesAsync()`, that is something I searched for and couldn't find. It probably is a management thing, but with the filter rules being persisted in the service, something like that seems even more important to me. Otherwise, how would I ever remember which filters have already been added in previous sessions? Or is there any other option specifically for filter management? I can't manage filters within the Azure portal or can I?

The try-catch solution has already appeared to me, but that is something I'd rather avoid if somehow possible. I'll have another look at the exception type and possible handling options on Monday, though.

I'll also have a look at the management sample library you referenced. From what I've read so far this sounds really interesting, although the AAD prerequisite scared me off a little :) Also, I'm not sure if we really want a new subscription for each application (or rather each iteration of just one application) and the `AutoDeleteOnIdle` option; we'll have to give that some thinking first. It seems a little messy, but might do the job on the other hand.

Right now for our prototype architecture it's probably okay to just remember the filter names and delete them one by one before recreating them; especially, since we might be able to just squeeze everything into one single `SqlFilter`. In a more advanced scenario, however, all this would still leave me a little nervous :)

Have a nice weekend and thanks again for sharing the insights and presenting me with all the different options.

**Comment by jtaubensee** [comment]
@papatoob - Previously you could do this from the `NamespaceManager` in our older package, but since we have not moved "management operations" to this library, we are lacking some features. I will mark this as a feature request to add `GetRulesAsync()`, but it might be a little bit until we are able to get to it.

To correct my previous point, I do not believe that there is a publicly documented way to check for rules from .NET Core, so handling the exceptions that you see is probably your best bet in the meantime.

**Comment by papatoob** [comment]
@jtaubensee Alright, thanks for the support. I'll definitely watch progress here, looking forward to future releases.

**Comment by SeanFeldman** [comment]
>  I do not believe that there is a publicly documented way to check for rules from .NET Core

Correct. It is not ATM.
Also `NamespaceManager.GetRulesAsync()` with a `filter` option is broken from what I have seen.

While it could be considered a management operation, unless provided by another package, should be by the client.

**Comment by SeanFeldman** [comment]
@nemakam is [`getRules`](https://github.com/Azure/azure-service-bus-dotnet/tree/getRules) branch addresses this issue? If it does, an accompanying PR would facilitate visibility into how it's implemented and  allow discussion.

**Comment by SeanFeldman** [comment]
Thank you @nemakam 🙂

**Comment by binzywu** [comment]
move to 1.0 as the code is ready but service is not.
